##############################################
#              UESL MCPlugin                 #
##############################################
#Config for Plugin

#Enable or Disable Custom Procosmetic Chest (Default true)
Procosmetic_Chest: true
#Enable or Disable Chat per world/region (Default true)
Chat_Changer: true
#At what player number should chat be global or bungee (Default 16)
Chat_Change_Value: 16

#Custom Join Channel (For Hub Servers)
Enable_Join_Channel: false
#Channel to set player when Joining Server
Join_Channel: global

#Parkour Database ID Name (Same as Parkour File)
Parkour:
  - PlanetParkour
  - ParkourParadise

#Channel List (Same as Channel File)
Channels:
  - global
  - disableregion
  - disableworld
  - hub
